"""Comment and Thread models for code reviews.

Two dataclasses: `Comment` (a single comment with author, body, file/line
anchor, and timestamp) and `Thread` (a list of comments grouped by file
and line). These are the data model for the review UI; persistence
happens in `storage.py`.

Docs: comment.doc.md
"""
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List, Optional


# ── Data models ────────────────────────────────────────────────────────
@dataclass
class Comment:
    """A single comment on a review.

    Fields:
      - `id`: UUID, generated by the server (`ReviewServer.add_comment`).
      - `review_id`: Foreign key to the review this comment belongs to.
      - `author`: Free-form author name (e.g. "reviewer", "agent", or a real name).
      - `body`: Comment text. The server enforces a 64 KB limit; see `server.py`.
      - `file`, `line`: Optional anchor — when both are set, the UI shows
        the comment on that file:line; otherwise it's a "general" comment
        on the whole review.
      - `created_at`: ISO 8601 UTC timestamp, generated automatically.
    """
    id: str
    review_id: str
    author: str
    body: str
    file: Optional[str] = None
    line: Optional[int] = 0
    # `default_factory` so each instance gets a fresh timestamp.
    # `timezone.utc` is correct even when local time is not UTC.
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass
class Thread:
    """A thread of comments on a specific file/line.

    The UI groups comments by `(file, line)` and renders each group as a
    collapsible thread. The `file` and `line` are part of the thread
    identity — two threads can have the same `comments` list but
    different anchors.
    """
    file: Optional[str]
    line: Optional[int]
    comments: List[Comment] = field(default_factory=list)
